package com.appblish.filora.feature.settings

import android.content.ActivityNotFoundException
import android.content.Intent
import android.net.Uri
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.verticalScroll
import androidx.compose.material3.HorizontalDivider
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.platform.testTag
import androidx.compose.ui.semantics.Role
import androidx.compose.ui.semantics.role
import androidx.compose.ui.semantics.semantics
import androidx.compose.ui.unit.dp

/** Privacy-policy destination shown on the About screen (FR-11). */
private const val PRIVACY_POLICY_URL = "https://appblish.com/filora/privacy"

/**
 * About screen (M13 T139, FR-11): app version, the open-source licenses Filora
 * ships, and outbound links (privacy policy). Stateful entry — it resolves the
 * platform [LocalContext] only to fire link [Intent]s, so [AboutContent] stays a
 * pure function of its inputs and can be exercised without Android.
 */
@Composable
fun AboutScreen(
    versionName: String,
    modifier: Modifier = Modifier,
) {
    val context = LocalContext.current
    AboutContent(
        versionName = versionName,
        modifier = modifier,
        onOpenLink = { url ->
            // A missing browser must not crash the app; FR-11 links are best-effort.
            try {
                context.startActivity(
                    Intent(Intent.ACTION_VIEW, Uri.parse(url)).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK),
                )
            } catch (_: ActivityNotFoundException) {
                // No handler installed — nothing to open.
            }
        },
    )
}

/**
 * Stateless About surface. Hoisted out of [AboutScreen] so the layout and the
 * shipped [filoraOssLicenses] list can be rendered in previews and asserted in
 * tests without a launched activity.
 */
@Composable
fun AboutContent(
    versionName: String,
    modifier: Modifier = Modifier,
    onOpenLink: (String) -> Unit = {},
) {
    Column(
        modifier =
            modifier
                .fillMaxWidth()
                .verticalScroll(rememberScrollState())
                .padding(16.dp),
        verticalArrangement = Arrangement.spacedBy(20.dp),
    ) {
        Column(verticalArrangement = Arrangement.spacedBy(4.dp)) {
            Text(text = "Filora", style = MaterialTheme.typography.titleLarge)
            Text(
                text = "Version $versionName",
                style = MaterialTheme.typography.bodyMedium,
                color = MaterialTheme.colorScheme.onSurfaceVariant,
                modifier = Modifier.testTag("about_version"),
            )
        }

        HorizontalDivider()

        LinkRow(
            label = "Privacy policy",
            onClick = { onOpenLink(PRIVACY_POLICY_URL) },
            testTag = "about_privacy_policy",
        )

        HorizontalDivider()

        Text(
            text = "Open-source licenses",
            style = MaterialTheme.typography.titleSmall,
            color = MaterialTheme.colorScheme.primary,
        )
        filoraOssLicenses().forEach { license ->
            Column(verticalArrangement = Arrangement.spacedBy(2.dp)) {
                Text(text = license.name, style = MaterialTheme.typography.bodyLarge)
                Text(
                    text = license.license,
                    style = MaterialTheme.typography.bodySmall,
                    color = MaterialTheme.colorScheme.onSurfaceVariant,
                )
            }
        }
    }
}

@Composable
private fun LinkRow(
    label: String,
    onClick: () -> Unit,
    testTag: String,
) {
    Text(
        text = label,
        style = MaterialTheme.typography.bodyLarge,
        modifier =
            Modifier
                .fillMaxWidth()
                .clickable(onClick = onClick)
                .semantics { role = Role.Button }
                .testTag(testTag)
                .padding(vertical = 8.dp),
    )
}

/** A single open-source dependency credit shown on the About screen. */
data class OssLicense(
    val name: String,
    val license: String,
)

/**
 * The open-source libraries Filora bundles, with their licenses (FR-11, T139).
 *
 * Maintained by hand rather than generated by an OSS-licenses Gradle plugin so the
 * About screen carries no extra build dependency or plugin; keep this in sync when
 * a runtime dependency is added or removed.
 */
fun filoraOssLicenses(): List<OssLicense> =
    listOf(
        OssLicense("Jetpack Compose", "Apache License 2.0"),
        OssLicense("AndroidX (Core, Lifecycle, Navigation, DataStore, Room, WorkManager)", "Apache License 2.0"),
        OssLicense("Kotlin & Kotlin Coroutines", "Apache License 2.0"),
        OssLicense("Dagger Hilt", "Apache License 2.0"),
        OssLicense("Coil", "Apache License 2.0"),
        OssLicense("Material Components for Android", "Apache License 2.0"),
    )
